### PR TITLE
Added a migrations file naming convention as it falls it can be ambiguou...

### PR DESCRIPTION
**Pull request by karrde00**
The migration tool will not run when using hyphens in the filename

### CODE REVIEW

**Comment by nnnnathann** [comment]
Didn't know that it did that, added a commit to the migration generator to just strip dashes FYI, shouldn't be a problem in the future

https://github.com/oberd/OBERD/commit/28ba303d5ac5d6e3bdcf645da8ced80fc39754c0

**Comment by karrde00** [comment]
Awesome, thanks. Only found out on the last migration I made. Should still be a standard for it regardless. Keeps the naming uniform

**Comment by nnnnathann** [comment]
indeed

**Comment by elliottisonfire** [comment]
:+1:

**Pull request merged**
